## Introduction to Data Science

#### University of Redlands - DATA 101
#### Prof: Joanna Bieri [joanna_bieri@redlands.edu](mailto:joanna_bieri@redlands.edu)
#### [Class Website: data101.joannabieri.com](https://joannabieri.com/data101.html)

---------------------------------------
# Homework Day 6
---------------------------------------

GOALS:

1. Answer all the questions from the lecture.
2. Practice wrangling data - doing more advanced code
3. Complete your first more advanced Exploration/Exercise

----------------------------------------------------------

This homework has **4 Questions** and **7 Exercises**

NOTE:
Exercises will tend to be an analysis of a single piece of data where one exercise builds on the next.

In [54]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.defaule = 'colab'

from itables import show

In [55]:
file_location = 'https://joannabieri.com/introdatascience/data/hotels.csv'
DF_raw_hotels = pd.read_csv(file_location)

In [56]:
show(DF_raw_hotels)

In [57]:
# I always look at the column names - they have to be spelled exactly!
columns_list = list(DF_raw_hotels.keys())
print(columns_list)

['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date']

### Example of Combining Masks

* Show only results for visitors from USA or GBR.

In [58]:
mask = (DF_raw_hotels['country']=='USA') | (DF_raw_hotels['country']=='GBR')
DF_raw_hotels[mask]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119358,City Hotel,0,135,2017,August,35,30,1,4,2,...,No Deposit,14.0,NaN,0,Transient,143.10,0,1,Check-Out,2017-09-04
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,No Deposit,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07

## Example Finding unique values

In [59]:
my_columns = ['market_segment','customer_type']
DF_raw_hotels[my_columns].drop_duplicates()

       market_segment    customer_type
0              Direct        Transient
3           Corporate        Transient
4           Online TA        Transient
9       Offline TA/TO        Transient
16      Offline TA/TO         Contract
47      Offline TA/TO  Transient-Party
125     Complementary        Transient
127         Online TA  Transient-Party
260            Direct  Transient-Party
413            Groups  Transient-Party
417            Groups        Transient
539         Online TA            Group
1530        Corporate  Transient-Party
1539           Direct            Group
1587    Offline TA/TO            Group
2262        Corporate         Contract
2263           Direct         Contract
2698           Groups         Contract
9511    Complementary  Transient-Party
14051   Complementary            Group
14654          Groups            Group
15141       Corporate            Group
15261   Complementary         Contract
15506       Online TA         Contract
40600       Undefined  Transient-Party
49013        Aviation  Transient-Party
49372        Aviation        Transient
112102       Aviation            Group

## Example Counting unique values

In [60]:
my_columns = ['market_segment']
DF_raw_hotels[my_columns].value_counts()

market_segment
Online TA         56477
Offline TA/TO     24219
Groups            19811
Direct            12606
Corporate          5295
Complementary       743
Aviation            237
Undefined             2
Name: count, dtype: int64

## Example of Counting unique values in two columns - unsorted

In [61]:
my_columns = ['market_segment','customer_type']
DF_raw_hotels[my_columns].value_counts(sort=False)

market_segment  customer_type
Aviation        Group                  2
                Transient            218
                Transient-Party       17
Complementary   Contract               2
                Group                  6
                Transient            703
                Transient-Party       32
Corporate       Contract              22
                Group                 29
                Transient           3576
                Transient-Party     1668
Direct          Contract              14
                Group                134
                Transient          11336
                Transient-Party     1122
Groups          Contract             735
                Group                 16
                Transient           8427
                Transient-Party    10633
Offline TA/TO   Contract            1817
                Group                211
                Transient          14054
                Transient-Party     8137
Online TA       Contract            1486
                Group                179
                Transient          51299
                Transient-Party     3513
Undefined       Transient-Party        2
Name: count, dtype: int64

## Example of Saving Unique Values to a Data Frame

Just add the command **.reset_index().rename(columns={"index": "value", 0: "count"})**. In this class

In [62]:
my_columns = ['market_segment','customer_type']
my_counts = DF_raw_hotels[my_columns].value_counts()
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"})
show(my_counts)

## Example of Adding a column to a Data Frame

In [63]:
DF_raw_hotels['little_ones'] = DF_raw_hotels['children'] + DF_raw_hotels['babies']
DF_raw_hotels

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,little_ones
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,0.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,0.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,0.0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,0.0
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,0.0
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,0.0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,0.0

**Q1** Count up the number of little_ones in different hotel types (Hint - use value_counts() with hotel and little_ones as your columns.)

In [64]:
# Your code here: 
my_columns = ['little_ones']
DF_raw_hotels[my_columns].value_counts()

little_ones
0.0            110054
1.0              5446
2.0              3772
3.0               111
10.0                2
9.0                 1
Name: count, dtype: int64

**Q2** Add a new column that calculates the total number of humans (all_humans) in the room (adults+children+babies) (Hint - you can copy and paste the code above where we calculated little_ones and add on another thing)

In [65]:
# Your code here
my_columns = ['little_ones', 'adults', 'children', 'babies']
DF_raw_hotels[my_columns].value_counts()

little_ones  adults  children  babies
0.0          2       0.0       0         81557
             1       0.0       0         22577
             3       0.0       0          5665
1.0          2       1.0       0          3950
2.0          2       2.0       0          3221
1.0          2       0.0       1           708
             3       1.0       0           485
             1       1.0       0           277
2.0          0       2.0       0           205
0.0          0       0.0       0           180
2.0          1       2.0       0           155
             2       1.0       1           136
3.0          2       3.0       0            61
0.0          4       0.0       0            59
2.0          3       2.0       0            39
3.0          2       2.0       1            27
2.0          2       0.0       2            12
3.0          0       3.0       0            11
1.0          3       0.0       1            10
             1       0.0       1             9
0.0          26      0.0       0             5
1.0          0       1.0       0             4
3.0          1       3.0       0             4
             2       1.0       2             3
             0       2.0       1             3
             1       2.0       1             2
2.0          3       1.0       1             2
0.0          27      0.0       0             2
2.0          1       1.0       1             2
0.0          5       0.0       0             2
1.0          4       1.0       0             2
0.0          20      0.0       0             2
             40      0.0       0             1
1.0          4       0.0       1             1
0.0          6       0.0       0             1
             10      0.0       0             1
             55      0.0       0             1
             50      0.0       0             1
9.0          1       0.0       9             1
10.0         2       0.0       10            1
                     10.0      0             1
Name: count, dtype: int64

**Q3** Can you figure out what the code below is doing - comment on each line -- remember you can add a comment using the hashtag #

In [66]:
# PLEASE ADD YOUR COMMENTS!
DF_raw_hotels['little_ones'] = DF_raw_hotels['children'] + DF_raw_hotels['babies'] # Creating a new column summing children and babies
my_columns = ['hotel','little_ones'] # Keeping only the "hotel" and "little_ones" columns
my_counts = DF_raw_hotels[my_columns].value_counts() # Counting occurrences of each (hotel, little_ones) combination
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"}) # Renaming the columns, to look nice in a data frame.
my_counts['proportion']=my_counts['count']/sum(my_counts['count']) #  Adds a column to compute proportions

## Example of Grouping the data frame into chunks

In [67]:
my_columns = ['adults','children','little_ones','babies']
DF_raw_hotels.groupby(by=['hotel'])[my_columns].sum()

              adults  children  little_ones  babies
hotel
City Hotel    146838    7248.0       7640.0     392
Resort Hotel   74798    5155.0       5712.0     557

There are lots of different operaitons you could use:

* .min()
* .max()
* .mean()
* .median()
* .sum()
* .prod()
* .count()
* .describe()

Here we see that .describe() does all the descriptive statistics for each of columns, broken into the two groups. 

## Example of Grouping to quickly generate data

The .groupby() function lets you quickly generate data about things you care about. In just one command below we are able to look at the total number of occupants for each of the columns (adults, children, little_ones, and babies) for each month in the data set.

In [68]:
DF_raw_hotels.groupby(by=['arrival_date_month'])[my_columns].min(),
DF_raw_hotels.groupby(by=['arrival_date_month'])[my_columns].max(),
DF_raw_hotels.groupby(by=['arrival_date_month'])[my_columns].mean()

                      adults  children  little_ones    babies
arrival_date_month
April               1.876274  0.102895     0.107674  0.004780
August              2.002955  0.200389     0.214517  0.014124
December            1.826254  0.108555     0.120059  0.011504
February            1.791026  0.097918     0.105231  0.007313
January             1.690673  0.076235     0.084331  0.008096
July                1.987521  0.183398     0.192955  0.009557
June                1.860591  0.096627     0.103117  0.006491
March               1.804676  0.071472     0.077292  0.005820
May                 1.826732  0.071665     0.077771  0.006106
November            1.690904  0.041066     0.047689  0.006623
October             1.817115  0.062993     0.068548  0.005556
September           1.872954  0.056909     0.065188  0.008279

**Q4** Try changing the code above to calculate the mean, max, and min for the above data.

# Exercises:

## Our first big-ish problem:

Now you will try to use our hotels data set to answer some questions! You will need to use the tools we have learned so far to look into the data and try to answer the questions. Really try to answer the questions with as few hints as possible!

### IF YOU USE MY ANSWER - avoid plagiarism

To avoid plagiarism, if you end up copying my answer and using it, YOU MUST explain clearly what each part of the code is doing. It's okay to need to use my code at this point, but it is not helpful to your learning to blindly copy and paste without trying to understand.

**Hints and Answers can be found in the lecture notes!**

### Exercise 1

Are people traveling on a whim? 

Yes it looks like people are traveling on a whim

How could you find out?

I found out by creating a column that showed me all the lead times, then I had a code count all of the lead times. Then I was able to see the lead times that were less than 1 day.

Try creating a mask filtering for hotel bookings where the guest is **not** from the US (`country` code `"USA"`) and the `lead_time` is less than 1 day.

What proportion of people traveled last minute?

6174

In [74]:
# Your code here
my_columns = ['lead_time'] #I am first gathering data from these columns.
my_counts = DF_raw_hotels[my_columns].value_counts() #Im then counting all the data in these columns.
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"}) #Renaming the columns, to look nice in a data frame.
show(my_counts) 

mask = (DF_raw_hotels['country']!='USA') & (DF_raw_hotels['lead_time']<1) # I am hiding results from the USA with lead times greater than 1 
DF_final = DF_raw_hotels[mask]
len(DF_final)

6174

### Exercise 2

How many bookings involve at least 1 child **or** baby?   9332

In [75]:
# Your code here:
my_columns = ['children','babies'] #I am first gathering data from these columns.
my_counts = DF_raw_hotels[my_columns].value_counts() #Im then counting all the data in these columns.
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"})
show(my_counts) #Renaming the columns, to look nice in a data frame.

mask = (DF_raw_hotels['children']>0) | (DF_raw_hotels['babies']>0) #I am hiding the results of people with 0 babies or children
DF_final = DF_raw_hotels[mask]
len(DF_final) #This gives me the final number.

9332

### Exercise 3

Do you think it's more likely to find bookings with children or babies in city hotels or resort hotels?
Test your intuition.

You will find more bookings with children and babies at city hotels instead of resorts.

In [83]:
# Your code here:
my_columns = ['children','babies']
DF_raw_hotels.groupby(by=['hotel'])[my_columns].sum() #I grouped the columns of information I want to find out for city hotels and resort hotels, then I found the sum of these results.

              children  babies
hotel
City Hotel      7248.0     392
Resort Hotel    5155.0     557

### Exercise 4

Create a frequency table of the number of `adults` in a booking.
Display the results in descending order so the most common observation is on top.
What is the most common number of adults in bookings in this dataset?
Are there any surprising results?
The most common number of adults in a booking is 2. This is not surprising because usually couples (which consists of 2 adults) will book their own room.

In [94]:
# Your code here:
my_columns = ['adults',] 
my_counts = DF_raw_hotels[my_columns].value_counts() #Found the amount of adults who book for city hotel or resort rooms 
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"})
show(my_counts)

### Exercise 5

Repeat Exercise 5, once for canceled bookings (`is_canceled` coded as 1) and once for not canceled bookings (`is_canceled` coded as 0).
What does this reveal about the surprising results you spotted in the previous exercise?
This shows that more bookings are not canceled than are canceled.

In [96]:
# Your code here:
my_columns = ['is_canceled'] 
my_counts = DF_raw_hotels[my_columns].value_counts() #Found the number of cancellations and non-cancellations.
my_counts = my_counts.reset_index().rename(columns={"index": "value", 0: "count"})
show(my_counts)

### Exercise 6

Calculate minimum, mean, median, and maximum average daily rate (column labeled 'adr') grouped by `hotel` type so that you can get these statistics separately for resort and city hotels. (Hint - try using .describe() after doing group by)

Which type of hotel is higher, on average?
A city hotel is higher on average.

In [101]:
# Your code here: I grouped all the data that is known for the "hotel" column about adr, and I had the code describe it for me, which then gave me the min, mean, median, and max.
DF_raw_hotels.groupby('hotel')['adr'].describe()

                count        mean        std   min   25%   50%    75%     max
hotel
City Hotel    79330.0  105.304465  43.602954  0.00  79.2  99.9  126.0  5400.0
Resort Hotel  40060.0   94.952930  61.442418 -6.38  50.0  75.0  125.0   508.0

### Exercise 7

We observe two unusual values in the summary statistics above -- a negative minimum, and a very high maximum).
What types of hotels are these?

Locate these observations in the data set and find out the arrival date (year and month) as well as how many people (adults, children, and babies) stayed in the room.

You can investigate the data by showing the data frame to locate these values, but preferably you should identify them in a reproducible way with some code.

In [105]:
# Your code here: 
# Find the max
lookup = 5400 #Had it look up the max.

my_columns  =['hotel','arrival_date_year','arrival_date_month','adults','children','babies','is_canceled','adr'] #I looked up all the information a may want from these specific columns.
mask = DF_raw_hotels['adr']==lookup #masked the adr
show(DF_raw_hotels[mask][my_columns])

# Find the min
lookup = -6.38 #Had it look up the min.
mask = DF_raw_hotels['adr']==lookup #masked the adr
show(DF_raw_hotels[mask][my_columns])